### ISSUE TITLE
how can i transfer current request to proxypass request?

### ISSUE THREAD

**Issue by reynaldliu** [opentracing-contrib/nginx-opentracing#10]
English is not my native language, the following is translated by Google

How should I get the TraceId of the current request and put it in the header of http Pass in the next hop such as reverse proxy（proxy_pass ,upstream{}）.
X-B3-TraceId
X-B3-SpanId
X-B3-ParentSpanId
X-B3-Sampled
X-B3-Flags
I tried this setting unsuccessfully, in the back-end php-fpm did not get to this http header

e.g.
when i access
http://test.com/a.html   will make a  TraceId ==1234

1. a.html content

``
<html>
<link rel="stylesheet" href="a.css" type="text/css"/>
<script src="http://test.com/b.css"> </script>
<script src="http://test.com/c.js"> </script>
<body>
i am a.html
</body>
</html>

``

2.then c.js send a ajax request
http://test.com/cgi/d

how can i make a.html TraceId=1234
and b.css and c.js and cgi/d ParentSpanId=TraceId=1234 ?

**Comment by rnburn** [comment]
Not completely sure I understand what you're asking, but there's an option [proxy_pass_request_headers](https://github.com/opentracing-contrib/nginx-opentracing/blob/master/example/zoo/nginx.conf#L50) that can forward the request headers to the proxy if that's what you're looking for.

**Comment by rnburn** [comment]
@reynaldliu -- were you able to get this to work? If not, could try clarifying your question.

**Comment by rnburn** [comment]
Closing since I haven't gotten a response.

**Comment by bzon** [comment]
This is related to https://github.com/kubernetes/ingress-nginx/issues/4705
