### ISSUE TITLE
Support for SkyWalking

### ISSUE THREAD

**Issue by ltandfyy** [opentracing-contrib/nginx-opentracing#103]
I'm from China.I hope you can understand it.When can SkyWalking support be provided?

**Comment by rnburn** [comment]
SkyWalking would need to provide C++ tracer to be supported. Try asking them if that's on their roadmap.

**Comment by ltandfyy** [comment]
Oh, I see.Thank you very much.

**Comment by rnburn** [comment]
Closing since support wouldn't be provided directly by the nginx-opentracing package.
