### ISSUE TITLE
Question: g++ build requirements

### ISSUE THREAD

**Issue by ct27stf** [opentracing-contrib/nginx-opentracing#117]
https://github.com/opentracing-contrib/nginx-opentracing/blob/894927f8eb90daea4c2ad4c251b6151e93ac7c47/ci/build_module_binary.sh#L30

As referenced above, g++ needs to be ==7 or could it be >=7 ?
I'm doing some builds on Alpine linux which has 8.3.0 and it seems to be building ok so far

**Comment by rnburn** [comment]
It's not part of the CI coverage, but I don't see any reason why it shouldn't work. libstdc++ is ABI compatible between gcc 7 and 8 so you should be able to use the same binary.
