### ISSUE TITLE
Calling opentracing_propagate_context throws an error when opentracing is off

### ISSUE THREAD

**Issue by mike-quayle-very** [opentracing-contrib/nginx-opentracing#124]
We have opentracing switched on or off in different environments, controlled by an environmental variable. When opentracing is switched off the code in nginx.conf is essentially this:

```
load_module modules/ngx_http_opentracing_module.so;
http {
   opentracing_load_tracer /usr/local/lib/libjaegertracing_plugin.so /srv/src/main/resources/jaeger-nginx-config.json;
   opentracing off;
   upstream backend {
      server app-service:9001;
   }
   location ~ {
     opentracing_propagate_context;
     proxy_pass http://backend;
   }
}
```
However, the call: opentracing_propagate_context causes the following error to be logged for every request:

```
[error] 52#52: *31049 failed to expand opentracing_context_ for request 0000000001D58EB0: no OpenTracingContext attached to request
```
If opentracing is off, shouldn't this message be suppressed?

Mike

**Comment by verdie-g** [comment]
I have a similar issue on nginx 1.19.2 with open tracing only enable on one location.
```
load_module modules/ngx_http_opentracing_module.so;

http {
    # ...
    opentracing_trace_locations off;
    opentracing_load_tracer /usr/local/lib/libdd_opentracing_plugin.so /etc/nginx/dd-config.json;
    # ...

  server {
      listen 443 ssl http2;
      # ...

      location / {
          # ...
          opentracing on;
          opentracing_operation_name "$request_method $uri";
          opentracing_propagate_context;
      }
  }
}
```

All other locations seem to log the error `8517#8517: *2091 failed to expand opentracing_context_ for request 000055BCE99ABC60: no OpenTracingContext attached to request while logging request`.

**Comment by verdie-g** [comment]
The exception is [thrown here](https://github.com/opentracing-contrib/nginx-opentracing/blob/e0109dd801673a4506e0649f1ddaa313fa3ca1a2/opentracing/src/opentracing_variable.cpp#L50) when trying to expand a variable when opentracing is off.

A workaround I have found is to only use `opentracing*` variables in server blocks where opentracing is on.
```
load_module modules/ngx_http_opentracing_module.so;

http {
    # ...
    opentracing_trace_locations off;
    opentracing_load_tracer /usr/local/lib/libdd_opentracing_plugin.so /etc/nginx/dd-config.json;
    log_format default '...';
    log_format trace '... $opentracing_context_x_datadog_trace_id';
    access_log /var/log/nginx/access.log default;
    # ...

  server {
      listen 443 ssl http2;
      # ...

      location / {
          # ...
          opentracing on;
          opentracing_operation_name "$request_method $uri";
          opentracing_propagate_context;
          access_log /var/log/nginx/access.log trace;
      }
  }
}
```

When opentracing is off, variables should be expanded to `-` and no error logged.
