### ISSUE TITLE
Feat Request: Support W3C Trace Context header

### ISSUE THREAD

**Issue by Renz2018** [opentracing-contrib/nginx-opentracing#132]
W3C trace context now is "W3C Recommendation 06 February 2020"
But nginx-opentracing support B3 and jaeger, not support w3c trace context.
I know opentelemetry support W3c trace context dafault, but still many people use nginx-opentracing( specaily nginx-ingress-controller)

**Comment by robermorales** [comment]
+1

**Comment by miry** [comment]
It seems the Jaeger CPP should support W3C Format https://www.jaegertracing.io/docs/1.18/client-libraries/#propagation-format

**Comment by ovidiubuligan** [comment]
I also need this with a aspnet core backend . The backend only knows how to get the parent context  if it is in W3C format.

**Comment by miry** [comment]
I have successfully upgraded jaeger tracer to custom branch: https://github.com/opentracing-contrib/nginx-opentracing/compare/master...miry:upgrade-jeager-opentracing

It generates W3C. 
Going to prepare a PR.

**Comment by miry** [comment]
Created a sample PR https://github.com/opentracing-contrib/nginx-opentracing/pull/147 to show how it is possible to use latest Jaeger with W3C. There are no any changes required in nginx-opentracing code. 
Working on patching nginx-ingress to support latest libs.

**Comment by miry** [comment]
Jeager tracing released a new version where it supports W3C headers.
Ingress-nginx master has changes with latest jaeger.
