### ISSUE TITLE
Add support for nginx 1.18.0

### ISSUE THREAD

**Issue by entscheidungsproblem** [opentracing-contrib/nginx-opentracing#137]
Could you add support for some newer nginx versions? If 1.17.10 can be supported, 1.18.0 can be added as well since they are functionally the same ([here is the diff](https://github.com/nginx/nginx/compare/release-1.17.10...release-1.18.0))

https://github.com/opentracing-contrib/nginx-opentracing/blob/d00780bef5ef93ca41306dd06d5910a8267daff2/ci/build_module_binaries.sh#L6

**Comment by rnburn** [comment]
Fixed in #139
