### ISSUE TITLE
Question: Any chance to update opentracing-cpp to 1.6.0?

### ISSUE THREAD

**Issue by aledbf** [opentracing-contrib/nginx-opentracing#140]

**Comment by miry** [comment]
@aledbf pls check this PR: https://github.com/opentracing-contrib/nginx-opentracing/pull/143

The current implementation is working fine with Opentracing 1.6.0.

**Comment by aledbf** [comment]
> Do you think it is ok to stop support other traces (in ingress-nginx as well)?

Not really. That would be a breaking change for lots of users.
One of the implementors - datadog is waiting for this update to release a compatible version?
https://github.com/DataDog/dd-opentracing-cpp/issues/115#issuecomment-734490099

**Comment by miry** [comment]
@aledbf Did I understand correctly.dd-opentracing-cpp is compatible with Opentracing-cpp 1.6.0 ?

Need to recheck other traces, may be they also ready for upgrade.

For nginx-opentracing there are no changes required to support opentracing-cpp 1.6.0. 
I was blocked only by traces.

**Comment by miry** [comment]
@aledbf Released a new version of nginx-opentracing. Now it releases modules for Opentracing 1.5.1 and Opentracing 1.6 https://github.com/opentracing-contrib/nginx-opentracing/releases/tag/v0.14.0

The docker image uses Opentracing v1.6.0
