### ISSUE TITLE
nginx 1.19.6

### ISSUE THREAD

**Issue by esetnik** [opentracing-contrib/nginx-opentracing#148]
Is it save to use nginx-opentracing [v0.10.0](https://github.com/opentracing-contrib/nginx-opentracing/releases/tag/v0.10.0) with nginx v1.19.6?

**Comment by esetnik** [comment]
https://github.com/opentracing-contrib/nginx-opentracing/pull/142

**Comment by miry** [comment]
It works for development environment at least. There are no huge changes.

**Comment by esetnik** [comment]
@miry do you think this project is abandoned? I haven't seen any activity by the maintainers in awhile. @rnburn are you looking for more maintainers?

**Comment by rnburn** [comment]
No one is sponsoring this project right now.

But if someone wants to volunteer to be a maintainer I can grant them permissions.

**Comment by miry** [comment]
fixed in #150
