### ISSUE TITLE
Question: Is it possible to ignore tracing for ELB healthchecks?

### ISSUE THREAD

**Issue by Tyler-2** [opentracing-contrib/nginx-opentracing#157]
Our load balancer hits our nginx server to do health checks a lot. I've disabled logging for these requests, but of course the `opentracing` bits are still called. How can I instruct nginx or opentracing to ignore requests that meet a certain condition, such as user-agent?

**Comment by miry** [comment]
I could not answer how it should be done in nginx level, but I think you can drop traces on opentelemetry collector level.
https://opentelemetry.io/docs/collector/configuration/

**Comment by Tyler-2** [comment]
I used that last suggestion. I modified where our LB is hitting nginx for healthchecks and turned off tracing there.

```
    location /healthcheck {
        return 200 'Server is up.';
        add_header Content-Type text/plain;
        opentracing off;
    }
```

Thanks!
