### ISSUE TITLE
Huge container size 3.8G. Is it normal?

### ISSUE THREAD

**Issue by opteemister** [opentracing-contrib/nginx-opentracing#158]
I noticed that the compressed size of container image is 1.4G, but uncompressed is almost 4G. 
After quick look I found huge folder `/opentracing-cpp` in root folder with all build files, which seems hasn't been cleanup after build. 

I also found a reason. Seems this commit https://github.com/opentracing-contrib/nginx-opentracing/commit/894927f8eb90daea4c2ad4c251b6151e93ac7c47# is breaking the build because it splits executions where `tempDir` is set and where it is really used. 
So in fact all `cd "$tempDir"` commands do nothing.

**Comment by miry** [comment]
@opteemister As I see Dockerfile is used only for testing purpose and it has extra traces, that probably you don't need.
There is a [PR](https://github.com/opentracing-contrib/nginx-opentracing/pull/155) to have Opentracing 1.6 in the Dockerfile and it would remove most of traces from the built. 
Can you share your use case of the image?

**Comment by miry** [comment]
Updated the #155 to have less layers and clean the tmp folder. Now it have size of 1G.

**Comment by opteemister** [comment]
@miry strange that it is used only for testing purposes. 
Initially I found the image here https://hub.docker.com/r/opentracing/nginx-opentracing and also there is a mention about that docker images are provided to support using nginx with OpenTracing - https://github.com/opentracing-contrib/nginx-opentracing#docker

Our use case:
We are using OpenTracing integration for nginx to enable DD APM integration. https://docs.datadoghq.com/tracing/setup_overview/proxy_setup/?tab=nginx

**Comment by miry** [comment]
@opteemister next version would release image as 1GB. But I believe it still huge for production uses. For example if there autoscaling setup exists, it would be slow because to download 1GB would not be the fast solution.

Ideally need to tune image to have multi stage build and reduce size to 100 MB (similar to ingress-nginx).

**Comment by opteemister** [comment]
Thank you for your suggestion. I'll try to install libs by our own.

**Comment by miry** [comment]
@opteemister released a new version of [image](https://hub.docker.com/r/opentracing/nginx-opentracing/tags?page=1&ordering=last_updated):

![image](https://user-images.githubusercontent.com/21104/111679978-03dcce00-8822-11eb-9502-1ed17c2dbf89.png)
