### ISSUE TITLE
port 55680 is not listen by opentelemetry-collector in example/go/otel

### ISSUE THREAD

**Issue by zhuizhuhaomeng** [opentracing-contrib/nginx-opentracing#217]
https://github.com/opentracing-contrib/nginx-opentracing/tree/master/example/go/otel

I got the following error  in the terminal of `docker-compose up --build`  when execute `curl localhost:8081`
```
otel-app-1     | 2021/10/12 02:43:32 rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.18.0.3:55680: connect: connection refused"
```

**Comment by zhuizhuhaomeng** [comment]
@miry can you help with this?

**Comment by miry** [comment]
@zhuizhuhaomeng Can you check #218 if it works for you.
