### ISSUE TITLE
Building instructions are incomplete

### ISSUE THREAD

**Issue by carlosjgp** [opentracing-contrib/nginx-opentracing#23]
I can't build this dynamic library following the `README.md` instructions.
I try to replicate the process by using the same commands as the Docker image with no luck.

Can you please list the library versions compatible and tested with this module?

I also try to build only `opentracing-cpp` and `zipkin-cpp` libraries and only use those modules... 
Everything builds successfully but when I try to use the modules I have this error
```
2018/01/17 14:00:36 [emerg] 7#7: dlopen() "/etc/nginx/modules/ngx_http_zipkin_module.so" failed (Error loading shared library libcurl.so.4: No such file or directory (needed by /usr/local/lib/libzipkin.so.0)) in /etc/nginx/nginx.conf:5
nginx: [emerg] dlopen() "/etc/nginx/modules/ngx_http_zipkin_module.so" failed (Error loading shared library libcurl.so.4: No such file or directory (needed by /usr/local/lib/libzipkin.so.0))
```

**Comment by rnburn** [comment]
Not sure what distribution you're using, but zipkin-opentracing requires libcurl. On ubuntu, you can install it with `apt-get install libcurl4-openssl-dev`.

Or if you already have it installed in some non-standard location, you need to set up ld-config so that it can find it.

**Comment by rnburn** [comment]
The build instructions vary for which tracer backend you use. `curl` is listed as a dependency on https://github.com/rnburn/zipkin-cpp-opentracing, but it doesn't include installation instructions for it since that would depend on the environment you're using.

**Comment by rnburn** [comment]
@carlosjgp were you able to get this to work?

**Comment by carlosjgp** [comment]
I'm going to try the `ldconfig` suggestion...

Should I create a PR to update the documentation and make clear that these libraries are built for Debian/Ubuntu?

**Comment by rnburn** [comment]
They're not just for Debian/Ubuntu. `curl` is available for most platforms.

**Comment by rnburn** [comment]
Closing this since the `curl` dependency is listed on https://github.com/rnburn/zipkin-cpp-opentracing.

If you'd like an easier installation, you can put in a feature request for distribution packages.
