### ISSUE TITLE
Multi-environment tracing

### ISSUE THREAD

**Issue by mpiexec** [opentracing-contrib/nginx-opentracing#243]
Hello

Is it possible to use different settings (server, options) for multiple virtual servers at the same time?
Nginx config example:

```
http {
  server {
    server_name srv1;
    opentracing_load_tracer /usr/lib/libjaegertracing_plugin.so /etc/nginx/jaeger-config1.json;
    ...
  }
  server {
    server_name srv2;
    opentracing_load_tracer /usr/lib/libjaegertracing_plugin.so /etc/nginx/jaeger-config2.json;
    ...
  }
}
```

**Comment by miry** [comment]
@mpiexec You can update one of examples for experiments to prove your theory. Example: https://github.com/opentracing-contrib/nginx-opentracing/tree/master/example/go/otel
