### ISSUE TITLE
Dynamic opentracing operation name for each request

### ISSUE THREAD

**Issue by narayanasamyr** [opentracing-contrib/nginx-opentracing#29]
i am not able to set the opentracing_operation_name dynamically for each request. Lets say if i have a variable which is initialised to nil in conf file and later i am setting the value based on some if condition, now i want to set the opentracing_operation_name by using the value of the variable. 

**Scenario:**

set $test_variable nil;
blah...
blah...
proxy...
if (some-condition1) 
  set $test_variable opearionname1
if (some-condition2)
   set $test_variable opearionname2

opentracing_operation_name $test_variable

**Problem:**
Here the problem is the operation name is set on entry phase of the request (opentracing_request_instrumentor.cpp, line 92) , by that time the variable is not initialised so opentracing_operation_name set to nil.

**Solution:**

I just made change in on_log_request method (opentracing_request_instrumentor.cpp) to set the value of  opentracing_operation_name in request exit phase, after that am able to achieve the dynamic opentracing operation name (ie., am able to set the value of opentracing_operation_name dynamically for each request)

**Code change**
Added blow three lines in on_log_request method in opentracing_request_instrumentor.cpp file,

  auto core_loc_conf = static_cast<ngx_http_core_loc_conf_t *>(
                ngx_http_get_module_loc_conf(request_, ngx_http_core_module));

  auto loc_conf = static_cast<opentracing_loc_conf_t *>(
                ngx_http_get_module_loc_conf(request_, ngx_http_opentracing_module));

 request_span_->SetOperationName(get_request_operation_name(request_, core_loc_conf, loc_conf));

**Comment by rnburn** [comment]
Thanks, could you provide a PR.

**Comment by rnburn** [comment]
@narayanasamyr - could you put in a PR for this?... it looks like you made the changes: https://github.com/narayanasamyr/nginx-opentracing/commit/214a558034a14b1fd22139dd02b87a3225eb9eec

**Comment by narayanasamyr** [comment]
@rnburn PR provided
