### ISSUE TITLE
start nginx failed,`libopentracing.so.1 can not open`

### ISSUE THREAD

**Issue by zhzure** [opentracing-contrib/nginx-opentracing#311]
hi, thanks for this amazing repo!
when I run cmd
` ./nginx -t -c /etc/nginx/nginx.conf`
It output
`nginx: [emerg] dlopen() "/usr/local/nginx/modules/ngx_http_opentracing_module.so" failed (libopentracing.so.1: cannot open shared object file: No such file or directory) in /etc/nginx/nginx.conf:9`
but I do have this .so file:
``` bash
root@XXX:/usr/local/nginx/sbin# ./nginx -v
nginx version: nginx/1.22.0
root@XXX:/usr/local/nginx/sbin# ./nginx -t -c /etc/nginx/nginx.conf 
nginx: [emerg] dlopen() "/usr/local/nginx/modules/ngx_http_opentracing_module.so" failed (libopentracing.so.1: cannot open shared object file: No such file or directory) in /etc/nginx/nginx.conf:9
nginx: configuration file /etc/nginx/nginx.conf test failed
root@XXX:/usr/local/nginx/sbin# ll /usr/local/lib/libopentracing.so.1
lrwxrwxrwx 1 root staff 23 Aug 12 16:00 /usr/local/lib/libopentracing.so.1 -> libopentracing.so.1.6.0
```
I have been struggled for days, but i still can't figure it out, any help would be appreciated!

I have installed jaeger-cpp-client,followed [here](https://github.com/jaegertracing/jaeger-client-cpp)
I have installed opentracing-cpp, followed [here](https://github.com/opentracing/opentracing-cpp)
I have installed nginx-1.22.0 from source code,followed [here](https://github.com/opentracing-contrib/nginx-opentracing#building-from-source),using cmd like
``` bash
$ ./configure --add-dynamic-module=/root/nginx-opentracing/opentracing #where i download current repo
$ make && sudo make install
```
and I only add one line in `nginx.conf`,it just got so wrong..
```yaml
user nginx;
worker_processes auto;
pid /run/nginx.pid;
load_module modules/ngx_http_opentracing_module.so;

events {
    worker_connections 65535;
}
;
http {
# XXX
}

```

**Comment by miry** [comment]
@zhzure Check installation instructions: https://github.com/opentracing-contrib/nginx-opentracing/tree/master/example/trivial/ubuntu-x86_64

You can download module from Github release page. Example latest  https://github.com/opentracing-contrib/nginx-opentracing/releases/tag/v0.26.0

**Comment by zhzure** [comment]
> 



> @zhzure Check installation instructions: https://github.com/opentracing-contrib/nginx-opentracing/tree/master/example/trivial/ubuntu-x86_64
> 
> You can download module from Github release page. Example latest https://github.com/opentracing-contrib/nginx-opentracing/releases/tag/v0.26.0

thanks, I will try it asap
