### ISSUE TITLE
There isn't a release with "opentracing_load_tracer" support.

### ISSUE THREAD

**Issue by jmprusi** [opentracing-contrib/nginx-opentracing#34]
Hi! 

We are trying to use nginx-opentracing for some of our projects, and we are adding opentracing support to our openresty base (https://github.com/3scale/s2i-openresty)

We want to use the opentracing_load_tracer directive, but there isn't any release which supports this. 

Are you planning on releasing a new version of this project?

Thanks!

**Comment by rnburn** [comment]
Added a release thank you.

**Comment by jmprusi** [comment]
That was fast! Thanks @rnburn !
