### ISSUE TITLE
Allow passing tags in for things like hostname or ip

### ISSUE THREAD

**Issue by SEJeff** [opentracing-contrib/nginx-opentracing#36]
The `hostname` tag in an ingress controller pod ends up being the name of the container, something like `ingress-nginx-controller-xyzz123`. I'd like to use the kubernetes downward api to create an env var such as `NODE_NAME` that contains the actual hostname of the kubelet running. This way, traces from the ingress controller will show the actual hostname of the pod running this code.

It [doesn't appear](https://github.com/opentracing-contrib/nginx-opentracing/blob/3036b8963f64bd5cf4fb21c893fca9c4214ffa8d/jaeger/src/ngx_http_jaeger_module.cpp#L16-L35) to currently support passing tags to the tracer constructor.

**Comment by SEJeff** [comment]
@rnburn Yes I think that can work once a fix for jaegertracing/jaeger-client-cpp#105 makes it in. Thanks

**Comment by rnburn** [comment]
@SEJeff - can I close this?
