### ISSUE TITLE
php-fpm

### ISSUE THREAD

**Issue by blong14** [opentracing-contrib/nginx-opentracing#42]
Hello,

I'm using nginx to proxy to php-fpm. How do I forward a span context to this type of backend?  I can set a fastcgi_param that is available in my backend but I'm not sure what the variable names are. Please forgive my ignorance with php, nginx, c++, etc. Not my typical stack.

Anyway, this is what I'm more or less trying to do:

`fastcgi_param HTTP_UBER_TRACE_ID $opentracing_context_trace_id;`

`opentracing_propagate_context;` doesn't seem to pass the necessary HTTP headers to php-fpm, and from what I understand the only way to have this type of functionality is to pass via fastcgi_param.

Thanks so much for your time.

Ben

**Comment by blong14** [comment]
@rnburn thanks for the quick response!!

I'll wait for `opentracing_propagate_context` as that sounds like what I need (and I'm in no rush). 

Thanks again.

**Comment by blong14** [comment]
@rnburn just saw #43 and wanted to say thanks!

**Comment by rnburn** [comment]
@blong14 You're Welcome!

Fixed in #43. You can now use `opentracing_fastcgi_propagate_context`. See [here](https://github.com/opentracing-contrib/nginx-opentracing/tree/master/example/php/jaeger) for an example of how to set it up.
