### ISSUE TITLE
Support for Nginx 1.24.0

### ISSUE THREAD

**Issue by alekhrycaiko** [opentracing-contrib/nginx-opentracing#420]
Hi there, as of 2023-04-11 Nginx 1.24.0 has been released. Is there a plan or timeline for when nginx-opentracing will support this new version?

**Comment by miry** [comment]
Hi @alekhrycaiko 

It is easy to send PR.

Here is an example: https://github.com/opentracing-contrib/nginx-opentracing/pull/379
