### ISSUE TITLE
How can I pass trace_id from nginx to python-flask app server and associate these two trace into one  while I query traces in Jaeger UI?

### ISSUE THREAD

**Issue by betterlch** [opentracing-contrib/nginx-opentracing#456]
Hello,

I write a docker-compose contains `nginx-opentracing`, `jaegertracing/all-in-one`and `python flask web service`, I try to associate one request  trace_id in nginx and flask when I query traces in Jaeger UI, but I have no idea todo so, is there any advice?

I tried set `opentracing_propagate_context;` seems doen't work.

How about`proxy_set_header X-Trace-ID $opentracing_context_uber_trace_id;` and other options?

Thanks~~

**Comment by miry** [comment]
You are looking in correct place. Here is an example how to correctly setup propogation context https://github.com/opentracing-contrib/nginx-opentracing/tree/master/example/go/otel
There is no Python example, but you could use our test environment https://github.com/opentracing-contrib/nginx-opentracing/tree/master/test/environment

There are multiple propogation formats and it could be different HTTP headers to propogatate context.

**Comment by betterlch** [comment]
![截图20230619112924318](https://github.com/opentracing-contrib/nginx-opentracing/assets/46791163/0808ef0a-f8b8-4147-87ad-1c6817bad119)
Thanks , I have used set_global_textmap(JaegerPropagator()) to combining multiple propagators into single one and get my wished result.

**Comment by betterlch** [comment]
opentelemetry is very powerful, but there are little related sample documents, making it difficult for beginners to easily get started~
