### ISSUE TITLE
error：opentracing/dynamic_load.h：no the files or directory

### ISSUE THREAD

**Issue by tiddlerhxy** [opentracing-contrib/nginx-opentracing#48]
I use building from source,when make && make install ，make a mistake，the following information：

In file included from /usr/local/nginx-opentracing-master/opentracing//src/ngx_http_opentracing_module.cpp:1:0:
/usr/local/nginx-opentracing-master/opentracing//src/load_tracer.h:3:38: 致命错误：opentracing/dynamic_load.h：没有那个文件或目录
 #include <opentracing/dynamic_load.h>
                                      ^
编译中断。
make[1]: *** [objs/addon/src/ngx_http_opentracing_module.o] 错误 1
make[1]: *** 正在等待未完成的任务....
make[1]: Leaving directory `/usr/local/nginx-1.14.0'
make: *** [build] 错误 2

**Comment by rnburn** [comment]
You need to install [opentracing-cpp](https://github.com/opentracing/opentracing-cpp) first.

**Comment by tiddlerhxy** [comment]
I have installed  opentracing-cpp, but when i make && make install ，another mistake,the following information:

/usr/local/nginx-opentracing-0.5.0/opentracing/src/discover_span_context_keys.cpp: 在构造函数‘ngx_opentracing::{anonymous}::HeaderKeyWriter::HeaderKeyWriter(ngx_pool_t*, std::vector<opentracing::v2::string_view>&)’中:
/usr/local/nginx-opentracing-0.5.0/opentracing/src/discover_span_context_keys.cpp:18:32: 错误：用类型为‘<brace-enclosed initializer list>’的右值初始化类型为‘std::vector<opentracing::v2::string_view>&’的非常量引用无效
       : pool_{pool}, keys_{keys} {}
                                ^
make[1]: *** [objs/addon/src/discover_span_context_keys.o] 错误 1
make[1]: *** 正在等待未完成的任务....
make[1]: Leaving directory `/root/nginx-1.14.0'
make: *** [build] 错误 2

**Comment by tiddlerhxy** [comment]
I upgraded the GCC version to 5.5，solve the problem.
