### ISSUE TITLE
Assert are missing on v0.33.0 release

### ISSUE THREAD

**Issue by cbeauchesne** [opentracing-contrib/nginx-opentracing#527]
Hi team,

Compared to [v0.32.0](https://github.com/opentracing-contrib/nginx-opentracing/releases/tag/v0.32.0), they are no asset (appart the source code) in the [v0.33.0](https://github.com/opentracing-contrib/nginx-opentracing/releases/tag/v0.33.0) release, is it expected ? 

Best,
Charles

**Comment by miry** [comment]
@lucacome It seems Github token expired for last release.

https://app.circleci.com/pipelines/github/opentracing-contrib/nginx-opentracing/1195/workflows/b6cd0b19-46be-4f4d-aad9-647ecdfe52bc/jobs/7431

**Comment by lucacome** [comment]
Hi @cbeauchesne 

sorry about that, the assets are there now. We should probably move that job to GitHub Actions to prevent this from happening again.
