### ISSUE TITLE
Question: is supported to request x-b3-sampled when sample_rate=0?

### ISSUE THREAD

**Issue by aledbf** [opentracing-contrib/nginx-opentracing#54]
```
curl -kvL -H "x-b3-sampled: 1" -H "x-b3-flags: 1" app.platform-testing.testing.k8.atcloud.io 2>/dev/null | grep -i sampled
    "x-b3-sampled": "0",
```

**Comment by Stono** [comment]
It's my understanding that debug mode eg `x-b3-flags: 1` should force a sample.

**Comment by Stono** [comment]
Anyone got any thoughts on this?  We're in a bit of a sticky situation at the moment where we're running with 10% sampling due to our throughput, but then our monitoring tests need to always be sampled, and they're not - so we're losing our ability to debug services.

**Comment by rnburn** [comment]
Those headers need to contain a full span context or they'll be ignored.

If you want to control the sampling, you can use the [sampling.priority](https://github.com/opentracing/specification/blob/master/semantic_conventions.md) tag.

But the zipkin library would need a PR to support it.

**Comment by Stono** [comment]
Bugger.

**Comment by rnburn** [comment]
Closing since this would be a https://github.com/rnburn/zipkin-cpp-opentracing issue
