### ISSUE TITLE
Question: Have you considered certification as an Nginx Plus module? 

### ISSUE THREAD

**Issue by willgittoes-dd** [opentracing-contrib/nginx-opentracing#60]
https://www.nginx.com/partners/certified-module-program/

Getting certified allows the module to be used by nginx plus supported installations, although I can't find much info about what the certification process entails.

Whatever work that process entails is potentially something I'd be happy to do myself. However before I reach out to Nginx to ask for more details, I wanted to get your (@rnburn) opinion first.

**Comment by willgittoes-dd** [comment]
Thanks for responding! That's sort-of what I expected (although OpenResty runs arbitrary Lua code, so...). 

My first hope was to get this module certified, but the back-up plan would be a statically-linked/combined vendor-specific tracer module that gets certified. What would be your feelings on that, given that only some part of the benefit (ie whatever improvements nginx ask for) could be contributed back here?

**Comment by rnburn** [comment]
That's the approach we were considering. I'm not sure what other options there are.

Would it be possible to set up this module up so that it could support bundling that way with vendor tracers without requiring separate forks to be maintained?

**Comment by willgittoes-dd** [comment]
My plan was to do something like:

- Git submodule nginx-opentracing into $MY_TRACER
- Build a single module from the two, to be certified
- Any suggestions made by Nginx that pertain to the nginx-opentracing part of the codebase, contribute upstream to nginx-opentracing (and if they seem pertinent to zipkin, at least make a Github issue or document it)

By using git submodule and contributing any needed changes, forking is prevented and improvements can be shared as best as is possible. It does mean more complexity on the implementation side, because some changes require buy in from all of nginx, $MY_TRACER, and also yourself/nginx-opentracing. But that doesn't seem so bad.

**Comment by tedsuo** [comment]
@willgittoes-dd just getting caught up. That sounds like a good solution, given the options. 

We could also open the discussion with NGINX again about certifying nginx-opentracing, as it's been a while. If I recall, the concern was that they did not want to have the OT certification somehow imply that any tracer you linked to it would also be covered by the certification. But we could see if they would be open to the idea that the certification specifically requires you to link to a certified tracer. That seems a lot cleaner IMHO.

**Comment by rnburn** [comment]
Closing since the module is now listed on https://www.nginx.com/products/nginx/modules/
