### ISSUE TITLE
Docker images are not updated automatically anymore

### ISSUE THREAD

**Issue by lucacome** [opentracing-contrib/nginx-opentracing#622]
After https://github.com/opentracing-contrib/nginx-opentracing/pull/606
- dependabot is not been able to automatically update the Dockerfile anymore
- the workflow that keeps the images up to date is not working anymore.

**Comment by lucacome** [comment]
What was the reason for the change @miry ?

**Comment by miry** [comment]
@lucacome it was problem with building a new image as I could remember.

As I understand the https://github.com/opentracing-contrib/nginx-opentracing/pull/606/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L204 pointed to `bookworm`

but we used `bullseye` for repo: https://github.com/opentracing-contrib/nginx-opentracing/pull/606/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L206

@lucacome can you share what worklfows were impacted?

**Comment by lucacome** [comment]
@miry dependabot doesn't resolve the `ARG`s unfortunately. Also this workflow https://github.com/opentracing-contrib/nginx-opentracing/actions/workflows/update-docker-images.yml has been failing.

I can update it to make it work again, I just wanted to know the reason for the change before starting to work on it.

**Comment by miry** [comment]
@lucacome my bad :( . pls fix it
