### ISSUE TITLE
Make Openresty image public on GitHub

### ISSUE THREAD

**Issue by lucacome** [opentracing-contrib/nginx-opentracing#647]
The Openresty image on GitHub is private https://github.com/opentracing-contrib/nginx-opentracing/pkgs/container/openresty and I don't have permission to make it public.

@miry do you have permissions or do we need @rnburn ?

**Comment by miry** [comment]
@lucacome As I remember it is done on Organisation Level - I don't have permissions

**Comment by lucacome** [comment]
The image is now public
