### ISSUE TITLE
nginx-opentracing compile error

### ISSUE THREAD

**Issue by jaminlu** [opentracing-contrib/nginx-opentracing#69]
my compilation environment is: 
gcc(cc) gcc (GCC) 5.1.0;
cmake version 3.6.2;
 nginx1.10.3
,but when i compiled nginx and generated the  ngx_http_opentracing_module.so file normally,the following error occurred to execute /usr/local/nginx/sbin/nginx -t:
nginx: [emerg] dlopen() "/usr/local/nginx/modules/ngx_http_opentracing_module.so" failed (/usr/local/nginx/modules/ngx_http_opentracing_module.so: undefined symbol: _ZN11opentracing11v3_unstable29DynamicallyLoadTracingLibraryEPKcRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE) in /usr/local/nginx/conf/nginx.conf:2
![image](https://user-images.githubusercontent.com/32287480/48878061-d265ba80-ee40-11e8-965b-8c2c9ce1e0f9.png)

i run command:
 nm  ngx_http_opentracing_module.so |grep Dynamic：
0000000000008820 W _ZN11opentracing11v3_unstable20DynamicLibraryHandleD0Ev
0000000000008890 W _ZN11opentracing11v3_unstable20DynamicLibraryHandleD1Ev
0000000000008890 W _ZN11opentracing11v3_unstable20DynamicLibraryHandleD2Ev
                 U _ZN11opentracing11v3_unstable29DynamicallyLoadTracingLibraryEPKcRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
0000000000009710 T _ZN15ngx_opentracing11load_tracerEP9ngx_log_sPKcS3_RN11opentracing11v3_unstable27DynamicTracingLibraryHandleERSt10shared_ptrINS5_6TracerEE
0000000000008830 W _ZNSt10unique_ptrIKN11opentracing11v3_unstable27DynamicTracingLibraryHandleESt14default_deleteIS3_EED1Ev
0000000000008830 W _ZNSt10unique_ptrIKN11opentracing11v3_unstable27DynamicTracingLibraryHandleESt14default_deleteIS3_EED2Ev
000000000000e600 r _ZZNR11opentracing11v3_unstable8expectedINS0_27DynamicTracingLibraryHandleESt10error_codeEdeEvE19__PRETTY_FUNCTION__
 
![image](https://user-images.githubusercontent.com/32287480/48877921-5c615380-ee40-11e8-8e9e-d20d47b3de7d.png)

runcommand: grep DynamicallyLoadTracingLibrary * -R
![image](https://user-images.githubusercontent.com/32287480/48877793-dba25780-ee3f-11e8-8178-5554d3c3fae6.png)

vim ngx_http_opentracing_module.so can find the function definition:
![image](https://user-images.githubusercontent.com/32287480/48878009-9df1fe80-ee40-11e8-8788-f11b474c7f9d.png)

Does anyone know the possible cause?or may it related to the gcc version?

**Comment by rnburn** [comment]
The prefix `_ZN11opentracing11v3_unstable20` shows that you compiled against the master branch of OT. Try using the latest release 1.5 instead. You're probably mixing incompatible OT library versions.
