### ISSUE TITLE
Missing modules/ngx_http_opentracing_module.so

### ISSUE THREAD

**Issue by EduardoAC** [opentracing-contrib/nginx-opentracing#79]
Currently, I am trying to find where is the module or source code to build the module `ngx_http_opentracing_module.so`. 

There is not any information within the repository and tutorial how to obtain that module

**Comment by rnburn** [comment]
What do you mean? The source code is in the repository and there are instructions on how to build the module in the README https://github.com/opentracing-contrib/nginx-opentracing#building-from-source

**Comment by EduardoAC** [comment]
@rnburn thanks for your quick answer and sorry for the delay.

These instructions are not clear how you can fetch. After some digging in this repository, there is a [good example](https://github.com/opentracing-contrib/nginx-opentracing/tree/master/example/trivial/ubuntu-x86_64) containing what I was looking for
```
wget -O - https://github.com/opentracing-contrib/nginx-opentracing/releases/download/v0.4.0/linux-amd64-nginx-1.14.0-ngx_http_module.so.tgz \
      | tar zxf -
```
This explain how to fetch the module from the releases. Perhaps, it will be good to guide users how to find this file.
