### ISSUE TITLE
Question: Can I configure a sampling rate?

### ISSUE THREAD

**Issue by kop** [opentracing-contrib/nginx-opentracing#8]
Hi,

Thank you for this module, looks really great.
However, I'm a little bit scary to enable this on production nginx. I was not able to find any control on amount tracing spans to create. Do I understand correctly that it will create a span for every request?

For high production traffic, it would be great to have an option to trace only, let's say, 0.5% or 1% of the requests.

**Comment by rnburn** [comment]
Sampling is usually done as a feature of the tracing libraries. I'm ok adding it to [zipkin-cpp-opentracing](https://github.com/rnburn/zipkin-cpp-opentracing) and exposing it as an option.

I believe the Jaeger implementation already has a feature for [this](https://github.com/isaachier/nginx-opentracing/blob/master/jaeger/src/ngx_http_jaeger_module.cpp#L146), though I don't know if it's quite ready for use yet.

**Comment by kop** [comment]
@rnburn thank you for the answer.

Jaeger is the tracer I'm using and I'm asking because I don't know any way how to configure this in Jaeger agent. This option is available in all Jaeger client libraries and I was expecting it to be here too.

It would be great to have such option.

**Comment by rnburn** [comment]
Adding @isaachier, @yurishkuro to see if they can answer.

I think the library is still under development so it may not have all the options yet.

**Comment by isaachier** [comment]
Yes there is a way and I have a fork of this project in development now. Builds on docker but haven't tested it yet.

**Comment by yurishkuro** [comment]
while Jaeger clients provide a way to configure sampling priority, the default mode we recommend is letting the clients pull the sampling strategy from Jaeger backend (cf. https://github.com/jaegertracing/jaeger/issues/365).

**Comment by rnburn** [comment]
@kop I think this is the [option](https://github.com/opentracing-contrib/nginx-opentracing/blob/master/jaeger/doc/Directives.md#jaeger_reporter_local_agent_host_port) to set the agent host and port if that's what you're looking for.

**Comment by kop** [comment]
> while Jaeger clients provide a way to configure sampling priority, the default mode we recommend is letting the clients pull the sampling strategy from Jaeger backend (cf. jaegertracing/jaeger#365).

This sounds great and should be much easier to work with, however this is something from the future. We still need a way to set sampling rate for current usage.

> @kop I think this is the option to set the agent host and port if that's what you're looking for.

Thank you, this is not exactly what was my question about :)

**Comment by rnburn** [comment]
@kop I just put in some fixes to make the Jaeger module work. I just did some testing and I believe writing something like this in your nginx.conf will give you what you want:
```
 http {
    opentracing on;
    jaeger_service_name test-nginx;
    jaeger_sampler_type probabilistic;
    jaeger_sampler_param 0.01; # Sample 10% of requests.
    jaeger_sampler_max_operations 500;
```
But note that there's a bug in Jaeger if you try to use a sample param of 100% (https://github.com/jaegertracing/cpp-client/issues/6).

@isaachier -- Could you document the different options available for [jaeger_sampler_type](https://github.com/opentracing-contrib/nginx-opentracing/blob/master/jaeger/doc/Directives.md#jaeger_sampler_type)? I had to grep through Jaeger's code to find this.

**Comment by isaachier** [comment]
Sure thing. Not sure when but soon enough.

**Comment by rnburn** [comment]
Closing. If you also want sampling for zipkin, please put in an issue to https://github.com/rnburn/zipkin-cpp-opentracing.
