### ISSUE TITLE
Support `X-B3-TraceId` headers only

### ISSUE THREAD

**Issue by sta-szek** [opentracing-contrib/nginx-opentracing#84]
Hi guys, 
I have issue when I send `X-B3-TraceId` header **only** -- it means without other headers like `X-B3-SpanId`, ...

I see error message:

```
2019/02/14 08:18:09 [error] 2480#2480: *2690023 failed to extract an opentracing span context from request 00005624140F3D60: opentracing: SpanContext data corrupted in Extract carrier, client: x.x.x.x, server: xxx.com, request: "PUT /some/path HTTP/1.1", host: "xxx.com"
```

Is there any chance that you can add support for sending `X-B3-TraceId` only?
You could take this trace id and use it for span id, etc.

My motivation is following:
We could change all our clients to send additional headers as well but we are waiting for official W3C tracing headers spec and we don't want to change it twice.

Thanks

**Comment by sta-szek** [comment]
anyone there? :)

**Comment by rnburn** [comment]
Interpreting the headers is the job of the tracers (e.g. https://github.com/rnburn/zipkin-cpp-opentracing) -- this module just passes them through.

If you want to add that feature (and there's precedent in other zipkin tracers), you can put in a PR to that project.
