### ISSUE TITLE
Set opentracing context for a request in an earlier phase

### ISSUE THREAD

**Issue by ElvinEfendi** [opentracing-contrib/nginx-opentracing#85]
I'm working on https://github.com/kubernetes/ingress-nginx/pull/3783 to enable tracing of each Nginx phase we run Lua code. I've noticed that `ngx.var.opentracing_binary_context` is not set at `rewrite` phase and when I try to access it in Lua I get:

```
2019/02/20 14:40:54 [error] 42#42: *374 failed to expand opentracing_context_ for request 0000564FD8E6D060: no OpenTracingContext attached to request, client: 172.17.0.1, server: example.com, request: "GET /echo HTTP/1.1", host: "example.com"
```

Looking at the source code, I noticed that opentracing runs after rewrite phase: https://github.com/opentracing-contrib/nginx-opentracing/blob/9cde691471eee8152484462f748486f595007464/opentracing/src/ngx_http_opentracing_module.cpp#L172

Can we inject it at `NGX_HTTP_POST_READ_PHASE` or `NGX_HTTP_SERVER_REWRITE_PHASE`? According to http://nginx.org/en/docs/dev/development_guide.html#http_phases `NGX_HTTP_POST_READ_PHASE` is the earliest phase.

**Comment by rnburn** [comment]
I think that would be ok. Can you try making the change and seeing if it breaks anything?

**Comment by ElvinEfendi** [comment]
I'll give it a try, but not sure when.

**Comment by terrynsun** [comment]
I moved it to the SERVER_REWRITE phase, because when I moved it earlier than the SERVER_REWRITE phase, the module doesn't get loaded for subrequests. This seems to work fine for me.

**Comment by ElvinEfendi** [comment]
@terrynsun SERVER_REWRITE  is probably good enough, maybe open a PR so that the maintainer can help with tests.

**Comment by rnburn** [comment]
Done in https://github.com/opentracing-contrib/nginx-opentracing/pull/98
