### ISSUE TITLE
Error reporting using openresty

### ISSUE THREAD

**Issue by JiZhangXiong** [opentracing-contrib/nginx-opentracing#86]
Using openresty alone to start the error reporting, the error information is as follows:
![1](https://user-images.githubusercontent.com/47075576/53156796-18c2e500-35fb-11e9-892c-212a8734dafd.png)
If using the Official Directory example and starting with Docker can work properly, Then I use the official website example to start without docker, report the same error, and start the openresty command:
/ usr/local/openresty/nginx/sbin/nginx-p `pwd`-c conf/nginx.conf

Why is this?

**Comment by JiZhangXiong** [comment]
Why do I use the official example and docker boots up normally?
![2](https://user-images.githubusercontent.com/47075576/53159523-0055c900-3601-11e9-9fac-da65cb774a5e.png)
![3](https://user-images.githubusercontent.com/47075576/53159534-05b31380-3601-11e9-8d25-5404157722d1.png)

**Comment by JarenGlover** [comment]
So the above is working as expected correct? 

What example are you running/using that is giving you the error?

**Comment by JiZhangXiong** [comment]
Above is an example of how the official website works，The problem now is that I don't need docker to deploy and run to report errors.

**Comment by JarenGlover** [comment]
>The problem now is that I don't need docker to deploy and run to report errors.
Are you saying when you are running openresty outside the docker container ... you are getting the above error? 

Are you sure you have the [opentracing-cpp](https://github.com/opentracing/opentracing-cpp) installed? When I had that error I resolved it by making sure the `opentrcing-cpp` was installed and had ran `ldconfig`.

**Comment by JiZhangXiong** [comment]
[ 12%] Building CXX object CMakeFiles/opentracing.dir/src/propagation.cpp.o
[ 25%] Building CXX object CMakeFiles/opentracing.dir/src/dynamic_load.cpp.o
[ 37%] Building CXX object CMakeFiles/opentracing.dir/src/noop.cpp.o
[ 50%] Building CXX object CMakeFiles/opentracing.dir/src/tracer.cpp.o
[ 62%] Building CXX object CMakeFiles/opentracing.dir/src/tracer_factory.cpp.o
[ 75%] Building CXX object CMakeFiles/opentracing.dir/src/ext/tags.cpp.o
[ 87%] Building CXX object CMakeFiles/opentracing.dir/src/dynamic_load_unix.cpp.o
[100%] Linking CXX shared library output/libopentracing.so

**Comment by JiZhangXiong** [comment]
Install configuration: "Release"
-- Up-to-date: /usr/local/include/opentracing
-- Installing: /usr/local/include/opentracing/config.h
-- Installing: /usr/local/include/opentracing/version.h
-- Installing: /usr/local/lib/libopentracing.so.1.5.1
-- Installing: /usr/local/lib/libopentracing.so.1
-- Up-to-date: /usr/local/lib/libopentracing.so
-- Up-to-date: /usr/local/include/opentracing/expected
-- Installing: /usr/local/include/opentracing/expected/expected.hpp
-- Up-to-date: /usr/local/include/opentracing/variant
-- Installing: /usr/local/include/opentracing/variant/recursive_wrapper.hpp
-- Installing: /usr/local/include/opentracing/variant/variant.hpp
-- Up-to-date: /usr/local/include/opentracing
-- Installing: /usr/local/include/opentracing/value.h
-- Up-to-date: /usr/local/include/opentracing/ext
-- Installing: /usr/local/include/opentracing/ext/tags.h
-- Installing: /usr/local/include/opentracing/dynamic_load.h
-- Installing: /usr/local/include/opentracing/propagation.h
-- Installing: /usr/local/include/opentracing/tracer.h
-- Installing: /usr/local/include/opentracing/string_view.h
-- Installing: /usr/local/include/opentracing/symbols.h
-- Installing: /usr/local/include/opentracing/tracer_factory.h
-- Installing: /usr/local/include/opentracing/util.h
-- Installing: /usr/local/include/opentracing/span.h
-- Installing: /usr/local/include/opentracing/noop.h
-- Old export file "/usr/local/lib/cmake/OpenTracing/OpenTracingTargets.cmake" will be replaced.  Removing files [/usr/local/lib/cmake/OpenTracing/OpenTracingTargets-release.cmake].
-- Installing: /usr/local/lib/cmake/OpenTracing/OpenTracingTargets.cmake
-- Installing: /usr/local/lib/cmake/OpenTracing/OpenTracingTargets-release.cmake
-- Installing: /usr/local/lib/cmake/OpenTracing/OpenTracingConfig.cmake
-- Installing: /usr/local/lib/cmake/OpenTracing/OpenTracingConfigVersion.cmake

**Comment by JiZhangXiong** [comment]
Is this installation successful?

**Comment by rnburn** [comment]
@JiZhangXiong - yes, that look like it installed.

If you need further help setting it up, you can ask on https://gitter.im/opentracing/public
