### ISSUE TITLE
openresty and nginx-opentracing

### ISSUE THREAD

**Issue by JarenGlover** [opentracing-contrib/nginx-opentracing#87]
Do you envision adding a pre-compiled binary for openresty in the Github releases?
 
Today the openresty bundles with nginx `1.13.6`. However, the binary you provide is `1.13.12`.

I can tell from [this](https://github.com/opentracing-contrib/nginx-opentracing/blob/1c8c2dcd15fe911b7040dac788d0537c0de3c97e/Dockerfile-openresty) you have openresty support. However, I got lost in the moving parts.

It looks like in order to build for openresty the dependencies are opentracing-cpp, lua bridger tracer and jaeger correct?  

I suspect if given a pre-compiled binary I would still have compiled openresty with the right flags to work with dynaimc modules.

**Comment by rnburn** [comment]
Could you update [this list](https://github.com/opentracing-contrib/nginx-opentracing/blob/master/ci/build_module_binaries.sh#L6) with the latest versions you'd like and they'll be bundled in the next release.

**Comment by JarenGlover** [comment]
closed by #88

**Comment by lketired** [comment]
Hello! Are you planning to release the pre-compiled binary (.so) for the openresty with nginx 1.13.6 anytime? I tried to compile in my setup, but getting into one issue after the other.
