### ISSUE TITLE
Question: Remotely controlled sampler for Jaeger?

### ISSUE THREAD

**Issue by reynaldiwijaya** [opentracing-contrib/nginx-opentracing#90]
I noticed that `jaeger-client-cpp` supported remotely controlled sampler (in which, it will consult the sampler for sample type and rate). I am using nginx ingress and asked them about this feature, noticing that their `opentracing.json` template does not include the parameter to define the URL https://github.com/kubernetes/ingress-nginx/issues/3894#issuecomment-473081063

But it seems nginx opentracing is not enabling this feature, is it correct?

**Comment by rnburn** [comment]
You can specify that option in the JSON config you pass to the tracer with the [opentracing_load_tracer](https://github.com/opentracing-contrib/nginx-opentracing/blob/master/doc/Reference.md#opentracing_load_tracer) directive.
