### ISSUE TITLE
Question: is arm supported?

### ISSUE THREAD

**Issue by aledbf** [opentracing-contrib/nginx-opentracing#91]
Error: https://github.com/kubernetes/ingress-nginx/pull/3852#issuecomment-469664089
**Note:** arm64 works fine

**Comment by rnburn** [comment]
That build error's coming from the Jaeger tracer which has boost as one of the dependencies. I would an issue into [jaeger-client-cpp](https://github.com/jaegertracing/jaeger-client-cpp) or maybe its build system [hunter](https://github.com/ruslo/hunter).

**Comment by aledbf** [comment]
@rnburn thanks!

**Comment by alexellis** [comment]
@aledbf can you reference any other issues here so that we can follow the papertrail?
