### ISSUE TITLE
How to set the request path as trace name?

### ISSUE THREAD

**Issue by nevi-me** [opentracing-contrib/nginx-opentracing#92]
I'm using the latest Docker image, proxying traffic to gRPC servers. I have a location like `service.v1.Service/`, and all traces for routes to that service aren't being named correctly to for example `service.v1.Service/GetData`.
Is there a way to enable this to be the span name?

**Comment by rnburn** [comment]
You can use [opentracing_operation_name](https://github.com/opentracing-contrib/nginx-opentracing/blob/master/doc/Reference.md#opentracing_operation_name) and [opentracing_location_operation_name](https://github.com/opentracing-contrib/nginx-opentracing/blob/master/doc/Reference.md#opentracing_location_operation_name) to change the names

**Comment by rnburn** [comment]
Closing. If you're still having trouble, you can reopen the issue.
